// <auto-generated />
using System;
using GatherApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GatherApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250214102733_TestDb7")]
    partial class TestDb7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ActivityActivityType", b =>
                {
                    b.Property<int>("ActTypesId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityPostId")
                        .HasColumnType("int");

                    b.HasKey("ActTypesId", "ActivityPostId");

                    b.HasIndex("ActivityPostId");

                    b.ToTable("ActivityActivityType");
                });

            modelBuilder.Entity("GatherApp.Models.Activity", b =>
                {
                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActDatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CloseDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleMapLink")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OpenDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Province")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("PostId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("GatherApp.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("GatherApp.Models.Application", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppliedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("AppliedStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FileAttached")
                        .HasMaxLength(4000000)
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("GatherApp.Models.Notification", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GatherApp.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverPageImg")
                        .HasMaxLength(4000000)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurParticipant")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.Property<bool>("IsAttached")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipant")
                        .HasColumnType("int");

                    b.Property<string>("PostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("GatherApp.Models.PostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("GatherApp.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfileImg")
                        .HasMaxLength(4000000)
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.Property<int>("LikedPostsId")
                        .HasColumnType("int");

                    b.Property<string>("User1Id")
                        .HasColumnType("varchar(36)");

                    b.HasKey("LikedPostsId", "User1Id");

                    b.HasIndex("User1Id");

                    b.ToTable("PostUser");
                });

            modelBuilder.Entity("ActivityActivityType", b =>
                {
                    b.HasOne("GatherApp.Models.ActivityType", null)
                        .WithMany()
                        .HasForeignKey("ActTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GatherApp.Models.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivityPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GatherApp.Models.Activity", b =>
                {
                    b.HasOne("GatherApp.Models.Post", "Post")
                        .WithOne("Activity")
                        .HasForeignKey("GatherApp.Models.Activity", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("GatherApp.Models.Application", b =>
                {
                    b.HasOne("GatherApp.Models.Post", "Post")
                        .WithMany("Applications")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GatherApp.Models.User", "User")
                        .WithMany("ApplyHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GatherApp.Models.Notification", b =>
                {
                    b.HasOne("GatherApp.Models.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GatherApp.Models.Post", b =>
                {
                    b.HasOne("GatherApp.Models.User", "User")
                        .WithMany("CreatedPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GatherApp.Models.PostLike", b =>
                {
                    b.HasOne("GatherApp.Models.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GatherApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostUser", b =>
                {
                    b.HasOne("GatherApp.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("LikedPostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GatherApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GatherApp.Models.Post", b =>
                {
                    b.Navigation("Activity")
                        .IsRequired();

                    b.Navigation("Applications");

                    b.Navigation("PostLikes");
                });

            modelBuilder.Entity("GatherApp.Models.User", b =>
                {
                    b.Navigation("ApplyHistories");

                    b.Navigation("CreatedPosts");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
